### ISSUE TITLE
How to use with Jest ?

### ISSUE THREAD

**Issue by Hyphon** [antfu/unplugin-auto-import#33]
version: 0.4.5
```
// MyComponent.tsx
export default defineComponent({
    // ....
})

// *.spec.ts
it('should render', () => {
    const wrapper = shallowMount(MyComponent)  // throw error: defineComponent is not defined
})
```

**Comment by Xa3lis** [comment]
Would be useful to me either

**Comment by Evertvdw** [comment]
@zynth17 @Xa3lis @Hyphon 
I just stumbled upon this as well, but I found a workaround/solution, inside the `jest.setup` file you can import the composables and set them on `global`. Like this:
```ts
import { useQuasar } from "quasar";
import { useRoute, useRouter } from "vue-router";
import { useStore } from "src/store";
import { computed } from "vue";

global.useQuasar = useQuasar;
global.useRoute = useRoute;
global.useRouter = useRouter;
global.useStore = useStore;
global.computed = computed;
```

If you use TS you will probably need to disable some type checking because otherwise it will complain that those properties are not defined on `Global` at runtime.

**Comment by valerih12** [comment]
@Evertvdw Thank you so much, it worked for me! If it'll help anyone, here is a quicker way to import everything from module (this was my case):

``` js
// jest.setup.js

import * as vue from 'vue'
for (const key of Object.keys(vue)) {
  global[key] = vue[key]
}
```

**Comment by antfu** [comment]
So I create a tools to (solve) this https://github.com/vitest-dev/vitest 👀
